theme: jekyll-theme-tactile
ORCID icon: [0000-0001-8464-3334](https://orcid.org/0000-0001-8464-3334) 
ORCID iD: ![ORCID iD icon](https://github.com/tadamus/cv/blob/gh-pages/ORCIDiD_icon32x32.png)
Name: Trisha Adamus
